/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultCopyRouteImport } from './routes/vault-copy'
import { Route as LeituraVaultRouteImport } from './routes/leitura-vault'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InformacoesPessoaisRouteImport } from './routes/informacoes-pessoais'
import { Route as ImportarClaudeRouteImport } from './routes/importar-claude'
import { Route as IndexRouteImport } from './routes/index'

const VaultCopyRoute = VaultCopyRouteImport.update({
  id: '/vault-copy',
  path: '/vault-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeituraVaultRoute = LeituraVaultRouteImport.update({
  id: '/leitura-vault',
  path: '/leitura-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacoesPessoaisRoute = InformacoesPessoaisRouteImport.update({
  id: '/informacoes-pessoais',
  path: '/informacoes-pessoais',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarClaudeRoute = ImportarClaudeRouteImport.update({
  id: '/importar-claude',
  path: '/importar-claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/importar-claude': typeof ImportarClaudeRoute
  '/informacoes-pessoais': typeof InformacoesPessoaisRoute
  '/insights': typeof InsightsRoute
  '/leitura-vault': typeof LeituraVaultRoute
  '/vault-copy': typeof VaultCopyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/importar-claude': typeof ImportarClaudeRoute
  '/informacoes-pessoais': typeof InformacoesPessoaisRoute
  '/insights': typeof InsightsRoute
  '/leitura-vault': typeof LeituraVaultRoute
  '/vault-copy': typeof VaultCopyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/importar-claude': typeof ImportarClaudeRoute
  '/informacoes-pessoais': typeof InformacoesPessoaisRoute
  '/insights': typeof InsightsRoute
  '/leitura-vault': typeof LeituraVaultRoute
  '/vault-copy': typeof VaultCopyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/importar-claude'
    | '/informacoes-pessoais'
    | '/insights'
    | '/leitura-vault'
    | '/vault-copy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/importar-claude'
    | '/informacoes-pessoais'
    | '/insights'
    | '/leitura-vault'
    | '/vault-copy'
  id:
    | '__root__'
    | '/'
    | '/importar-claude'
    | '/informacoes-pessoais'
    | '/insights'
    | '/leitura-vault'
    | '/vault-copy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportarClaudeRoute: typeof ImportarClaudeRoute
  InformacoesPessoaisRoute: typeof InformacoesPessoaisRoute
  InsightsRoute: typeof InsightsRoute
  LeituraVaultRoute: typeof LeituraVaultRoute
  VaultCopyRoute: typeof VaultCopyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault-copy': {
      id: '/vault-copy'
      path: '/vault-copy'
      fullPath: '/vault-copy'
      preLoaderRoute: typeof VaultCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leitura-vault': {
      id: '/leitura-vault'
      path: '/leitura-vault'
      fullPath: '/leitura-vault'
      preLoaderRoute: typeof LeituraVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacoes-pessoais': {
      id: '/informacoes-pessoais'
      path: '/informacoes-pessoais'
      fullPath: '/informacoes-pessoais'
      preLoaderRoute: typeof InformacoesPessoaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-claude': {
      id: '/importar-claude'
      path: '/importar-claude'
      fullPath: '/importar-claude'
      preLoaderRoute: typeof ImportarClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportarClaudeRoute: ImportarClaudeRoute,
  InformacoesPessoaisRoute: InformacoesPessoaisRoute,
  InsightsRoute: InsightsRoute,
  LeituraVaultRoute: LeituraVaultRoute,
  VaultCopyRoute: VaultCopyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
