/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultCopyRouteImport } from './routes/vault-copy'
import { Route as ImportarClaudeRouteImport } from './routes/importar-claude'
import { Route as IndexRouteImport } from './routes/index'

const VaultCopyRoute = VaultCopyRouteImport.update({
  id: '/vault-copy',
  path: '/vault-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarClaudeRoute = ImportarClaudeRouteImport.update({
  id: '/importar-claude',
  path: '/importar-claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/importar-claude': typeof ImportarClaudeRoute
  '/vault-copy': typeof VaultCopyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/importar-claude': typeof ImportarClaudeRoute
  '/vault-copy': typeof VaultCopyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/importar-claude': typeof ImportarClaudeRoute
  '/vault-copy': typeof VaultCopyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/importar-claude' | '/vault-copy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/importar-claude' | '/vault-copy'
  id: '__root__' | '/' | '/importar-claude' | '/vault-copy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportarClaudeRoute: typeof ImportarClaudeRoute
  VaultCopyRoute: typeof VaultCopyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault-copy': {
      id: '/vault-copy'
      path: '/vault-copy'
      fullPath: '/vault-copy'
      preLoaderRoute: typeof VaultCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-claude': {
      id: '/importar-claude'
      path: '/importar-claude'
      fullPath: '/importar-claude'
      preLoaderRoute: typeof ImportarClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportarClaudeRoute: ImportarClaudeRoute,
  VaultCopyRoute: VaultCopyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
